/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio */
        get: operations["salud_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modelo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadatos del modelo */
        get: operations["info_modelo_api_v1_modelo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tableros/aleatorio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Genera un tablero válido
         * @description Un tablero del juego base, listo para probar la app sin capturar nada.
         *
         *     Respeta el reparto de terrenos y fichas, y evita dejar dos números rojos
         *     (el 6 y el 8) en hexágonos adyacentes, como recomienda el reglamento.
         */
        get: operations["aleatorio_api_v1_tableros_aleatorio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tableros/validar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revisa un tablero
         * @description Comprueba un tablero contra las reglas del juego base.
         *
         *     Devuelve avisos en lugar de rechazarlo: el usuario puede estar a mitad de la
         *     captura, y bloquearlo ahí sería más molesto que útil.
         */
        post: operations["validar_api_v1_tableros_validar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recomendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recomienda dónde colocar los poblados iniciales
         * @description Devuelve las mejores opciones de colocación para este tablero.
         *
         *     Si no se pasa ``mio``, busca **parejas** de poblados: es la primera colocación.
         *     Si se pasa, busca el mejor **compañero** para ese vértice, que es lo que hace
         *     falta en la segunda colocación, cuando entre tu primer poblado y el segundo
         *     ya jugaron los demás y pueden haberte quitado el sitio.
         *
         *     Las opciones se devuelven de familias de estrategia distintas a propósito:
         *     tres opciones de expansión no ayudan a decidir, tres formas de jugar sí.
         */
        post: operations["recomendaciones_api_v1_recomendar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vision/tablero": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detecta el tablero a partir de una foto
         * @description Lee una foto del tablero **vacío** y devuelve los terrenos y números detectados.
         *
         *     La detección nunca se da por definitiva: la respuesta trae una confianza por
         *     hexágono para que la interfaz señale cuáles conviene revisar. El usuario
         *     confirma o corrige antes de calcular, así que un error de la visión es una
         *     corrección de dos clics y no una recomendación equivocada.
         */
        post: operations["leer_tablero_api_v1_vision_tablero_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pregunta sobre la recomendación
         * @description Responde dudas sobre las opciones que el usuario está viendo.
         *
         *     El asistente **no inventa recomendaciones nuevas**: contesta a partir del
         *     tablero y de las opciones que ya calculó el modelo. Si no hay clave de LLM
         *     configurada, responde con las explicaciones que genera el recomendador, así
         *     que la función nunca queda inservible.
         */
        post: operations["preguntar_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Arista */
        Arista: {
            /** Vertices */
            vertices: string[];
        };
        /** Body_leer_tablero_api_v1_vision_tablero_post */
        Body_leer_tablero_api_v1_vision_tablero_post: {
            /** Foto */
            foto: string;
        };
        /** Explicacion */
        Explicacion: {
            /** Titulo */
            titulo: string;
            /** Resumen */
            resumen: string;
            /** Produccion */
            produccion: string;
            /** Porque */
            porque: string[];
            /** Haz */
            haz: string;
            /** Evita */
            evita: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hexagono */
        Hexagono: {
            /**
             * Id
             * @description Coordenada axial, por ejemplo '0,-2'
             */
            id: string;
            /** Q */
            q: number;
            /** R */
            r: number;
            /**
             * Terreno
             * @enum {string}
             */
            terreno: "bosque" | "pastos" | "campos" | "colinas" | "montanas" | "desierto";
            /** Recurso */
            recurso?: ("madera" | "ladrillo" | "trigo" | "oveja" | "mineral") | null;
            /** Numero */
            numero?: number | null;
            /**
             * Pips
             * @default 0
             */
            pips: number;
        };
        /** HexagonoDetectado */
        HexagonoDetectado: {
            /** Id */
            id: string;
            /**
             * Terreno
             * @enum {string}
             */
            terreno: "bosque" | "pastos" | "campos" | "colinas" | "montanas" | "desierto";
            /** Numero */
            numero?: number | null;
            /** Confianza Terreno */
            confianza_terreno: number;
            /** Confianza Numero */
            confianza_numero: number;
        };
        /** InfoModelo */
        InfoModelo: {
            /** Variables */
            variables: string[];
            /** R2 Prueba */
            r2_prueba: number;
            /** Mae Prueba */
            mae_prueba: number;
            /** Estrategias */
            estrategias: string[];
        };
        /** Mensaje */
        Mensaje: {
            /**
             * Rol
             * @enum {string}
             */
            rol: "usuario" | "asistente";
            /** Texto */
            texto: string;
        };
        /** Opcion */
        Opcion: {
            /** Vertices */
            vertices: string[];
            /** Descripciones */
            descripciones: string[];
            /**
             * Prediccion
             * @description Puntos de victoria estimados en 20 rondas
             */
            prediccion: number;
            /** Estrategia */
            estrategia: string;
            explicacion: components["schemas"]["Explicacion"];
            /** Variables */
            variables: {
                [key: string]: number;
            };
        };
        /** PeticionChat */
        PeticionChat: {
            /** Pregunta */
            pregunta: string;
            /**
             * Historial
             * @default []
             */
            historial: components["schemas"]["Mensaje"][];
            tablero?: components["schemas"]["Tablero"] | null;
            /**
             * Opciones
             * @description Las recomendaciones que el usuario está viendo
             * @default []
             */
            opciones: components["schemas"]["Opcion"][];
            /**
             * Elegida
             * @description Índice (desde 0) de la opción que el usuario eligió en pantalla
             * @default 0
             */
            elegida: number;
        };
        /** PeticionRecomendar */
        PeticionRecomendar: {
            tablero: components["schemas"]["Tablero"];
            /**
             * Jugadores
             * @default 4
             */
            jugadores: number;
            /**
             * Ocupados
             * @description Vértices que ya tomaron otros jugadores
             * @default []
             */
            ocupados: string[];
            /**
             * Mio
             * @description Tu primer poblado, si ya lo colocaste. Con esto la búsqueda deja de ser de parejas y pasa a buscar el mejor compañero.
             */
            mio?: string | null;
            /**
             * Cuantas
             * @default 3
             */
            cuantas: number;
        };
        /** Puerto */
        Puerto: {
            /** Vertices */
            vertices: string[];
            /**
             * Tipo
             * @description '3:1' o el nombre de un recurso para el 2:1
             */
            tipo: string;
        };
        /** RespuestaChat */
        RespuestaChat: {
            /** Texto */
            texto: string;
            /**
             * Fuente
             * @description Si respondió el LLM o el motor de reglas del recomendador
             * @enum {string}
             */
            fuente: "modelo_de_lenguaje" | "plantillas";
        };
        /** RespuestaRecomendar */
        RespuestaRecomendar: {
            /**
             * Momento
             * @enum {string}
             */
            momento: "primera" | "segunda";
            /** Opciones */
            opciones: components["schemas"]["Opcion"][];
            /** Parejas Evaluadas */
            parejas_evaluadas: number;
            /**
             * Avisos
             * @default []
             */
            avisos: string[];
        };
        /** RespuestaVision */
        RespuestaVision: {
            tablero: components["schemas"]["Tablero"];
            /** Detecciones */
            detecciones: components["schemas"]["HexagonoDetectado"][];
            /**
             * Avisos
             * @default []
             */
            avisos: string[];
            /**
             * Mensaje
             * @description Qué debe revisar el usuario antes de calcular
             */
            mensaje: string;
        };
        /** Salud */
        Salud: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "ok" | "degradado";
            /** Version */
            version: string;
            /** Modelo Cargado */
            modelo_cargado: boolean;
            /** Chat Con Llm */
            chat_con_llm: boolean;
        };
        /** Tablero */
        Tablero: {
            /** Hexagonos */
            hexagonos: components["schemas"]["Hexagono"][];
            /**
             * Puertos
             * @default []
             */
            puertos: components["schemas"]["Puerto"][];
            /**
             * Vertices
             * @default []
             */
            vertices: components["schemas"]["Vertice"][];
            /**
             * Aristas
             * @default []
             */
            aristas: components["schemas"]["Arista"][];
            /** Semilla */
            semilla?: number | null;
        };
        /** TableroConAvisos */
        TableroConAvisos: {
            tablero: components["schemas"]["Tablero"];
            /**
             * Avisos
             * @description Incumplimientos de las reglas del juego base. No bloquean el cálculo.
             * @default []
             */
            avisos: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vertice */
        Vertice: {
            /** Id */
            id: string;
            /** Hexagonos */
            hexagonos: string[];
            /** Puerto */
            puerto?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
        };
    };
    info_modelo_api_v1_modelo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoModelo"];
                };
            };
        };
    };
    aleatorio_api_v1_tableros_aleatorio_get: {
        parameters: {
            query?: {
                /** @description Fija el azar para reproducir */
                semilla?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tablero"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validar_api_v1_tableros_validar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tablero"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableroConAvisos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recomendaciones_api_v1_recomendar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionRecomendar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaRecomendar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leer_tablero_api_v1_vision_tablero_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_leer_tablero_api_v1_vision_tablero_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaVision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preguntar_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionChat"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaChat"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
